### ISSUE TITLE
Error while submitting stats

### ISSUE THREAD

**Issue by alfdef1** [Bastian/bStats#103]
For a while, my server isn't able to submit stats to bstats.
Now I managed to grab this error:

https://hastebin.com/uganakudop.rb

**Comment by Bastian** [comment]
This error just means, that there was already a request in the last 30 minutes (to be precise, in a `XX:00-XX:30` or `XX:30-XX:00` window). This can sometimes happen after a restart and is no problem.

Why do you think that your server is not submiting stats?
If you are running multiple servers, make sure to not copy the bStats config file because every server needs a unique auto-generated id.
