### ISSUE TITLE
Feature request: Ignore global zeros

### ISSUE THREAD

**Issue by SlimeDog** [Bastian/bStats#138]
When (nearly) all plugins report 0 servers and 0 players, like at 2021-04-02 2100 (PDT), chances are the data are incorrect. Maybe they should not be included in the graphs.

**Comment by TheBusyBiscuit** [comment]
I agree that it looks a bit unsettling when you have large drops.
However interpolating data to make it look "smooth" wouldn't make the data more correct either since it would essentially be a manipulation.

I think the best solution here would be to have like a dark shaded area on the graph with a tooltip explaining that there was an incident. But that may not be as easy to implement with the charts system in use.

Furthermore, these "incidents" are not as straightforward to detect as you think.
The data itself isn't incorrect, it most often can be the result of server hosting providers experiencing downtime. And since not everyone uses the same server host, the data may vary a lot.
For example the incident you described never caused the server count for one our plugins to drop to zero. It had a few drops but it never really fell all the way down to zero. Probably because of some servers being home-hosted or simply unaffected by the incident.
![Screenshot 2021-04-03 121402](https://user-images.githubusercontent.com/3967898/113475491-54853580-9476-11eb-9f31-10046d5fbd7b.png)

So while "completely zero" cases may be detected easily, it would only be scratching the surface and probably not worth the effort in my opinion. And then again, the data isn't *incorrect* in of itself, just rather not representative and comparable to the rest of the year.

**Comment by SlimeDog** [comment]
Thanks for responding. I agree that the incorrect data represent the number of servers **reporting** at that instant, which for whatever reason could not reach the bStats server. It's just data. :)

**Comment by Bastian** [comment]
Hi, thank you for the suggestion :)

These gaps are usually **not** caused by Minecraft servers being down (like you seem to assume) but issues with bStats itself (networking problems of my hoster). This sadly has been a pretty persistent issue over the past few years and is nothing new.

In the past, I've used a script to clear these faulty data which then looks like this in the UI:
![example image](https://cdn.discordapp.com/attachments/283548939893080064/342689257716187137/gap.gif)

Since I migrated historic line chart data to Google's Firestore database, the script is no longer working. That's why you are still seeing these gaps. I will remove the broken datapoints soon (TM).


> However interpolating data to make it look "smooth" wouldn't make the data more correct either since it would essentially be a manipulation.

I don't agree. At the moment the data is definetly wrong. Deleting the incorrect data seems like the logical solution instead of keeping wrong data that does not reflect and real drops in Minecraft server or player counts. If this would not be a bStats issue but instead caused by something else (e.g., Mojang Auth servers being down), I would ofc. keep the data as is represents the real world data.

**Comment by TheBusyBiscuit** [comment]
Ah, I see now.  Thanks for the explanation!

**Comment by Bastian** [comment]
> networking problems of my hoster

I have to correct me. While it's usually networking issue, this time it was my fault not paying attention to the available disk space left.
![image of disk space left](https://user-images.githubusercontent.com/5033001/113477406-cadb6500-9481-11eb-899f-bda344a74756.png)

My Redis database didn't like it:
> Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

And in the logs:
> Write error saving DB on disk: No space left on device

Ooops.... ^^

**Comment by SlimeDog** [comment]
Bastian: Thank you for identifying the issue, and offering the correct explanation(s).

**Comment by SlimeDog** [comment]
So the feature request is more like: Check for full disk condition more frequently, and take appropriate action.

**Comment by Bastian** [comment]
The reason were a lot of unused old Docker images.
![screenshot of docker images](https://user-images.githubusercontent.com/5033001/113501903-0ed57500-9529-11eb-82fd-d3d6991af2b6.png)

I've set up a cronjob to purge them daily, so this should no longer be an issue.

**Comment by SlimeDog** [comment]
Sounds good. If you think it's resolved, please consider the issue closed.
