### ISSUE TITLE
Incorrect data shown on graph

### ISSUE THREAD

**Issue by wans2016** [Bastian/bStats#157]
Hello, I am using pterodactyl to start MC server, there are over 100 servers using the same IP. But only 16 of them are displayed on the chart, I don't know if you can add my IP to the IP whitelist, or is there any other way to solve it?
![image](https://user-images.githubusercontent.com/25297416/187020965-d2fed805-794b-4193-be5d-87b697296a4e.png)

**Comment by wans2016** [comment]
The ID of the plugin is 16267

**Comment by Bastian** [comment]
Hey, you're right: the problem is caused by your servers all using the same IP. This is a limit to make it harder for people to manipulate bStats data by faking thousands of Minecraft servers from a single server.

Unfortunately, this also blocks some legitimate requests, but the current limit has proven to be a good compromise for the vast majority of plugins and servers. There is no way to exclude individual IP addresses.

**Comment by wans2016** [comment]
Okay, can understand that, thank you
