### ISSUE TITLE
Opt-out by default :-(

### ISSUE THREAD

**Issue by ryantheleach** [Bastian/bStats#52]
To the detriment of statistics collection, It's looking more and more likely that Sponges plugin review guidelines are going to state that stats need to be opt-in by default.

This isn't a ticket to implement this yet, it may yet not make it into the guidelines.

I'm mostly asking to just see if you would be receptive to making the Sponge stats collection either:

1. Opt out by default.
2. Not send stats until the second run, if it remains opt-in by default.
3. Halt the server or nag the administrator to make an explicit choice, until it's dismissed (either opt in or opt out, as long as it's explicit and clear)
4. disable stats if snooper settings is disabled.

Do you have any other ideas? Parts of the team have been pretty vocal about at minimum not sending stats until users get a chance to opt out, if not need to opt-in for stats collection.

**Comment by MiniDigger** [comment]
all you have to do is to copy the classs (instead of shading it via maven or gradle if you do that), and changing the default config value to false here https://github.com/BtoBastian/bStats-Metrics/blob/master/bstats-sponge/src/main/java/org/bstats/sponge/Metrics.java#L301

I personally think that ppl should be manually opting out if they do not want stats. if we make it opt-in, you would loose like 90% of servers, not because they don't want stats, but because they don't care enough to enable it. so I am against point 1. I don't really get what you mean with point 2, do you want to give them a chance to change the generated config before sending stats? that could work I guess. 3 is an absolute no no, halting the server is never a good idea, it just annoys users. I don't think 4 is a proper solution either, they are two different settings and some users might be more comfortable with sending data to mojang via some stranger (or don't want to send to greedy microsoft but some friendly community member, you get the idea)

**Comment by DoNotSpamPls** [comment]
Nobody has had an issue with opt-out stats collecting for like 5 years, why should it become a problem now?

**Comment by ryantheleach** [comment]
>  2, do you want to give them a chance to change the generated config before sending stats? that could work I guess. 

That's the bare minimum of the teams current stance, yes. 

>all you have to do is to copy the classs (instead of shading it via maven or gradle if you do that), and changing the default config value to false here https://github.com/BtoBastian/bStats-Metrics/blob/master/bstats-sponge/src/main/java/org/bstats/sponge/Metrics.java#L301

The reason I was creating a ticket here, is that if this policy were to be in place, it's going to cause constant pain for the plugin developers who already shade to change the way they get bstats updates.

@MiniDigger @DoNotSpamPls I largely agree, I'm merely reaching out before the team reach a final decision to find out what bStats stance is.

**Comment by BtoBastian** [comment]
Is this discussion public somewhere and if yes, can you please link it to me?
I would be fine with the 2. option, but I'm not going to implement option 1 as this would make the stats completely useless. I would rather drop support for Sponge completely in that case.
I could understand it, if any sensible/private information would be send, but the data is really nothing special. Most of the users who complained about it, where users who didn't fully understand what bStats is doing.

**Comment by ryantheleach** [comment]
It's not yet public, nor is it completely settled.

Thanks.

**Comment by DoNotSpamPls** [comment]
Hey, is there an update on this? Did they make a final decision?

**Comment by MiniDigger** [comment]
Don't think so, they started a survey in their Twitter the other day.

**Comment by BtoBastian** [comment]
Btw: `Not send stats until the second run, if it remains opt-in by default.`
bStats waits 5 minutes after startup before sending its data. So it's not like the server owner has no chance to prevent it.

**Comment by DoNotSpamPls** [comment]
Hey again,

This is probably still a concern, since the Sponge team hasn't posted any results from the survey. I think enough has been said here, but I'd just like to share a story here...

Around 7 days ago Valve pushed out some privacy changes to Steam. I thought they were great at first, until I realised that, by default, your games are hidden to public eyes, you can now only see them if you're a friend. Sure, they give you the option to turn it back how it was, but who bothers with those kind of settings. I don't really mind that, but it goes much deeper than that. After doing some research, I found out that [SteamSpy](https://steamspy.com), a popular Steam game metrics service, can no longer function. Why? Because of that privacy change Valve made. Since they can no longer see who has which games, they can no longer provide reliable metrics to *tens of thousands* of developers, analysists and just random people. And the icicle on the cake? The only thing that is now hidden by default is the data that SteamSpy uses (and inventories, but that's fine). Actual data that can be linked to you, such as, but not limited to: joined groups, full name, achievements, screenshots, friend list.

If the proposed change by Sponge developers gets pushed, I feel like the same thing is going to happen as well (although on a much smaller scale). WIth opt-in metrics, you just can't get the same data, and the people who will actually turn it on, and the people that know what metrics are is pretty minor, compared to the average user base. Opt-in metrics are not a viable solution.

**Comment by DoNotSpamPls** [comment]
I think this can be closed, as the changed required by Sponge were already made.
