### ISSUE TITLE
Include server implementation in global/plugin stats

### ISSUE THREAD

**Issue by Phoenix616** [Bastian/bStats#57]
Currently the only way to get an overview what kind of servers are used is when the creators of these servers added statistics for their version under the Server Implementation category.

It would be a lot more useful if the plugin stats itself could read the server's implementation and report that. This way we could have some stats about distribution of different forks e.g. CraftBukkit vs. Spigot to decide which features our plugins can (not) support.

**Comment by BtoBastian** [comment]
Hey,

I agree that this information would be useful.
I will send this data with the release of the next Metric-Class.

**Comment by BillyGalbreath** [comment]
+1

Not sure why this isn't included as a default graph. Had to add my own:

https://bstats.org/plugin/bukkit/Ridables#server_type

**Comment by MiniDigger** [comment]
@Bastian, since this ticket is a few months old I am assuming you don't have time to look at this rn. Would you be open to accept a PR that collects the server mod (either via MinecraftServer#getServerModName or CraftServer#getName, spigot reports itself as craftbukkit there, but has changed the server mod name in the minecraftserver class...) and sends it to the backend? 
Even if nobody has time yet to make the backend actually handle that data, the earlier a new metrics class is release the sooner ppl will update, making the transition faster, leading to more servers that actually report that data when somebody actually implements the handling of the data in the backend and on the website.

**Comment by Bastian** [comment]
As far as I remember, the implementation is included in `Bukkit.getVersion();`.
I just made the mistake to parse the version number on the client instead of doing it on the server.
My suggestion would to just remove this parsing in the Metrics classes and do it on the server which makes it possible to also parse the implemention from it.
* Remove the client side parsing and just send the full `Bukkit.getVersion()` string
* On the server, you can just check if the version contains `MC: ` to decided if it's the plain version or includes information like the implementation as well -> The bStats backend already supports "hardcoded parsers", e.g. for the OS. See https://github.com/Bastian/bStats/blob/master/routes/submitData.js#L119 for example. This would just be another switch statement.

Thank you for wanting to make a PR for this, but this shouldn't be a lot of work to implement. I'll just quickly add it together with the next release of the Metrics classes (which will be released shortly after Sponge 7.1.0, as this will require an update anyway to make use of their new central config).

**Comment by Bastian** [comment]
https://bstats.org/global/bukkit#serverSoftware
This has been implemented for quite a while now :)

**Comment by Phoenix616** [comment]
I don't think this is fully implemented yet, only the global statistic seems to be available, not the per-plugin one. Or is that due to the difference in Metrics and MetricsLite?

**Comment by Bastian** [comment]
Newly registered plugins have the chart automatically.
For older plugins you have to create the chart as a custom chart like shown in this image: 
![image](https://user-images.githubusercontent.com/5033001/72827530-45ec9d00-3c7b-11ea-9af0-bf1a79f8582f.png)

Add the custom chart, wait ~30 minutes and the data should be visible :)

**Comment by Bastian** [comment]
The announcement on the Discord server: 
![image](https://user-images.githubusercontent.com/5033001/72827681-864c1b00-3c7b-11ea-9cd4-6a70e1df353d.png)
