### ISSUE TITLE
Clarify Privacy Policy

### ISSUE THREAD

**Issue by Foorack** [Bastian/bStats#63]
[https://bstats.org/privacy-policy](https://bstats.org/privacy-policy)

> Your personal data (e.g. name, e-mail address, ..) 
1. First of, two dots? Really?! To display a continuation of a series you always use three dots, and this ambiguity does not belong here. :slightly_smiling_face: 

2. ~~`e-mail` You are logging email addresses? How? And why?~~

3. Exactly what data is stored and for how long? Are IP-addresses logged? And if so, why? This should be stated/explained.

> For goods to be delivered, for instance, your name and address must be relayed to the supplier of the goods. 

> After expiry of deadlines as per tax-related and commercial regulations

4. ~~It looks like this is copied from a template as it does not relate to this website, as you are neither shipping nor selling anything.~~

**Comment by sgdc3** [comment]
Yep seems like a template, it should be updated properly @BtoBastian

**Comment by BtoBastian** [comment]
Hey,

yes, it is from a template (it's even linked there). German privacy laws are pretty strict and I'm no lawyer. Editing/Removing stuff from there without being very carefully might make it invalid and I don't want to risk anything. There are lawyers who just search for invalid imprints/privacy policies in order to sue the website owner.

About `2.`: E-Mails are oviosuly not stored atm, as you cannot enter one. I'll most likely add a "Forgot Password"-feature in the future which will require you to add an email to your account.

About `3.`: Ip adresses of users users are not stored at all. Ip-Adresses from servers are only stored for a Maximum of 31 minutes for ratelimiting.

**Comment by Foorack** [comment]
> Editing/Removing stuff from there without being very carefully might make it invalid and I don't want to risk anything. There are lawyers who just search for invalid imprints/privacy policies in order to sue the website owner.

Removing/correcting those paragraphs should not allow people to sue you. I am not familiar with German law but I can image people could only sue you regarding your privacy policy if it is stating something illegal or missing something which is required by law.

However, in the end those sentences does not matter as they are unrelated to your website, and therefore shouldn't hurt if they stay. I'll deprecate point 4 from my original post. :slightly_smiling_face: 

>  I'll most likely add a "Forgot Password"-feature in the future which will require you to add an email to your account.

I'll mark point 2 as done.

>  Ip adresses of users users are not stored at all. Ip-Adresses from servers are only stored for a Maximum of 31 minutes for ratelimiting.
Simply adding that line to the top of the privacy policy and removing the ".." would fix all the rest of the issues mentioned in the original report.

**Comment by Bastian** [comment]
The privacy policy has been updated in https://github.com/Bastian/bStats/commit/ad4ca06aa84258bf6b7f2880a5e865da57d9e920

It's still a template though
