### ISSUE TITLE
为什么地图上的台湾不在中国范围内 ?

### ISSUE THREAD

**Issue by Himmelt** [Bastian/bStats#77]
About The Map ,  Why Taiwan is not included in China ?

![image](https://user-images.githubusercontent.com/12007165/44591263-d35e6000-a7ef-11e8-9408-1ac4a90b8638.png)

**Comment by DoNotSpamPls** [comment]
Taiwan is listed as a seperate country, since that's how it's listed in the [ISO 3166-1](https://datahub.io/core/country-list) standard. While it *could* be renamed to `Taiwan, Province of China`, it will most likely not be included as part of China.

And no, I won't be going into Chinese politics territory.

**Comment by mbax** [comment]
Taiwan is *de facto* under jurisdiction of a separate political entity (ROC vs PRC) and hasn't been under the same control as mainland China for nearly 70 years.

**Comment by Bastian** [comment]
As @DoNotSpamPls said, bStats follows the ISO 3166-1 standard.

**Comment by nobodxbodon** [comment]
Got here from https://github.com/Bastian/bStats/issues/89. To clarify, being listed separately in ISO 3166-1 doesn't necessarily mean it's a separate country. As you can see in the [official ISO 3166 page for HK](https://www.iso.org/obp/ui/#iso:code:3166:HK):
![Screen Shot 2019-08-14 at 1 33 49 PM](https://user-images.githubusercontent.com/392497/63054160-30877180-be98-11e9-8cae-f3fb7e26d6e0.png)
The full name clearly states "the Hong Kong Special Administrative Region of China", and more importantly`Independent` is "No".

Similar with [TW](https://www.iso.org/obp/ui/#iso:code:3166:TW) and [MO](https://www.iso.org/obp/ui/#iso:code:3166:MO).

So this issue seems still valid?

**Comment by ljacqu** [comment]
Reading things like "derailing from the comply of ISO-3166-1" (from the other issue) shows to me that people don‘t understand what ISO-3166-1‘s purpose is, namely to provide standardized abbreviations. bStats follows the standard since anything it lists separately does use those abbreviations. This ISO standard does not make a political statement, nor does it say that you must include all of its entries if you start dividing the world into countries/geopolitical entities. 

So again, list Taiwan separately if you like, or don‘t, but ISO-3166 has nothing to do with that decision.

**Comment by LaxWasHere** [comment]
> _PR OR SHUT-UP_

**Comment by MiniDigger** [comment]
the issue is closed, that other one was even locked, please drag any political bullshit elsewhere. 

if you feel personally hurt by the fact that some country is displayed not like you want it displayed in your mind on a website that shows stats for modifications of minecraft out of all things, bastian already said that he is happy to accept any PRs that improve the situation but unless somebody actually steps up to do that, continuing these political topics is just a waste of time. 

or to use Lax's words "PR or shut up".

**Comment by nobodxbodon** [comment]
I'm all for focusing on the actual issues. I also agree it makes sense to follow ISO standard.

To repeat my point, it's important to keep in mind that, being listed separately in ISO 3166-1 doesn't necessarily mean it's a separate country, and the `Independent` attribute in the ISO tells that. Another example is Antarctica. 

That said, I don't see any impacts to end user, as there's no UI elements to mislead them to think every separate entity on the map stands for a separate country, so I don't see action item for now, other than changing the name of Taiwan to "Taiwan (Province of China)" according to its short name in [ISO](https://www.iso.org/obp/ui/#iso:code:3166:TW). Will create PR soon.

**Comment by heipiao233** [comment]
If it doesn't mean it's a separate country, it's OK.

**Comment by MiniDigger** [comment]
It's separate enough that it makes sense that the data should be collected and displayed separately

**Comment by nobodxbodon** [comment]
@heipiao233 be aware of the names that are not following ISO 3166-1, including `Taiwan (Province of China)`. Details see https://github.com/Bastian/bStats/pull/102
