### ISSUE TITLE
Add Paper to main menu drop down

### ISSUE THREAD

**Issue by aikar** [Bastian/bStats#78]
Hi,
I am a core team member of [Paper](https://github.com/PaperMC/Paper), the leading alternative to Spigot for better performance/more features/bug fixes/better developer api.

I was hoping we could get Paper added to the drop down under Bukkit / Spigot, to provide faster access to our metrics.

https://bstats.org/plugin/server-implementation/Paper

and can we have a /global/paper to match too?

Thanks!

**Comment by aikar** [comment]
@DoNotSpamPls we have a separate page already as I linked above.

So I guess exclude Paper from Bukkit/Spigot?

At this point, Paper, while compatible with Bukkit/Spigot plugins, is a VERY different project, and needs to be treated as such.
We are hoping to continue to grow our market share, and would appreciate better accuracy on our growth rates.

**Comment by BillyGalbreath** [comment]
Paper is also missing a global page:

https://bstats.org/global/paper

**Comment by Bastian** [comment]
Hey,

I think you misunderstand what the global charts are and how they are calculated. They are not a "shortcut" to a `server-implementation`, but use the data which is sent by the plugins.
Paper does not have it's own API and users don't develop plugins explicitly for Paper, but for the Bukkit-API in general. And this is what the global charts display: Which API the plugin uses (aka. which Metrics class: https://github.com/Bastian/bStats-Metrics ).

There's also no distinction between Bukkit and Spigot (which may be added as a pie-chart in the future).

**Comment by BillyGalbreath** [comment]
> Paper does not have it's own API and users don't develop plugins explicitly for Paper

Uh... Yes it does, and yes they do...

**Comment by MiniDigger** [comment]
> Paper does not have it's own API and users don't develop plugins explicitly for Paper

thats not true, you can see all the api editions here:
https://github.com/PaperMC/Paper/tree/master/Spigot-API-Patches
https://destroystokyo.com/javadocs/overview-summary.html
there are plugins that strictly require paper to make use of such features.

**Comment by Miclebrick** [comment]
"Bukkit" nowadays is not really a separate project as it's maintained by Spigot, the only use case for it is not wanting game behavior to be changed. Paper, on the other hand, is a different project maintained by different people, so it should be displayed separately. +1 for giving Paper its own stats

**Comment by MiniDigger** [comment]
ideally, every plugin should submit the server brand they use. just because a plugin uses the bukkit metrics class doesn't mean the server running it runs bukkit/spigot. I would argue that there is value for a plugin author to know that 40% of his users run paper or taco or whatever other downstream project there is because he could then assess if its worth spending time using api features of those projects.
for example, a warp plugin could make use of papers async chunk loading api to preload warp locations instead of just teleporting a player and forcing a sync chunk load. if just a few % of the users of the plugin do use paper, spending time of that would be wasted and could be better spend elsewhere, but if he knows that a large amount of his users use paper, he can look into implementing such a feature.

**Comment by Bastian** [comment]
> I would argue that there is value for a plugin author to know that 40% of his users run paper or taco or whatever other downstream project there is because he could then assess if its worth spending time using api features of those projects.
for example, a warp plugin could make use of papers async chunk loading api to preload warp locations instead of just teleporting a player and forcing a sync chunk load. if just a few % of the users of the plugin do use paper, spending time of that would be wasted and could be better spend elsewhere, but if he knows that a large amount of his users use paper, he can look into implementing such a feature.

For this a pie-chart would be sufficient though.

**Comment by BillyGalbreath** [comment]
Not o ly the pie chart per plugin (goal of #57), but a global metric would be nice (the goal of this ticket)

**Comment by MiniDigger** [comment]
with the data that #57 will collect, we could add a pie chart to https://bstats.org/global/bukkit which displays the server mod. 
all bukkit forks will use the same metrics class/endpoint, so I can see why you don't want to add new global pages, but a global distinction between server mods would make sense to have on that page.

(and also add paper to the title :D)

**Comment by aikar** [comment]
Anything reasonable that shows a difference in stats within the bukkit platform is good with me.

**Comment by Miclebrick** [comment]
This is probably the most political GitHub on GitHub

**Comment by Bastian** [comment]
https://bstats.org/global/bukkit#serverSoftware
There's a new pie chart now that shows this information. 👍
